src/matToVcf.cpp
Use program_options positional_options_description to check that no extra words are included on the command line (there are no positional options).
Add a warning for empty string in Mutation chrom, since the chrom is used in the output VCF.  [Pull request forthcoming for several spots in usher.cpp where a Mutation is copied, but only its position and nucleotides, not its chrom and is_missing.]
=> matToVcf: check no positional options, warn about empty string in chrom.

src/mutation_annotated_tree.cpp, src/mutation_annotated_tree.hpp, src/usher.cpp
I moved the mutation-copying code in mutation_annotated_tree.cpp's get_tree_copy to Mutation.copy() in mutation_annotated_tree.hpp, and updated usher.cpp to use Mutation.copy instead of just copying position and *_nuc, so that chrom would be copied as well (also is_missing).  Previously when new samples were added and saved to a new protobuf, the new protobuf would have the empty string for chrom of copied mutations.  Then matToVcf would write VCF with empty chrom for some mutations and non-empty chrom for others, when they should have been merged (same chrom).
=> Copy chrom along with position and *_nuc.

README.md, src/matUtils.cpp, src/mutation_annotated_tree.cpp, src/mutation_annotated_tree.hpp
This PR includes a total rework of how commands for matUtils are being handled to follow a new streamlined workflow. matUtils is now divided into three segments; annotate adds values to the protobuf, filter removes data from the protobuf, and convert produces non-protobuf files. A matUtils workflow will naturally call annotate, then filter, then convert to produce a dataset of interest.  The README has been updated accordingly.
This PR also includes updates to node creation methods and the matUtils annotate command to maintain metadata data values as the tree is recondensed and saved, as well as automatically recondensing the tree after annotation before storage. These should not interfere with the primary Usher package. 
It's notable that there is a significant bug with the Filter …
=> New subcommand structure and condensing

README.md, parsimony.proto, src/matUtils.cpp, src/mutation_annotated_tree.cpp, src/mutation_annotated_tree.hpp
This PR includes three major changes. The first is to the command structure, incorporating the new lineage-assignment function under the annotate heading, including an updated help message as well. The second is debugging and implementing neighborhood size calculation, which is a quality metric being the longest direct traversable path between two equally parsimonious placements within a set of at least two equally parsimonious placements for a given sample (smaller is better). Generally, a sample with high EPPs where all placements are nearby on the tree will have a low neighborhood score, while a sample with two EPPs on very different parts of the tree will have a high neighborhood score. Third, I've implemented a simple EPPs-based filtering loop under matUtils filter, which can be used …
=> Command restructure, neighborhood size, and EPPs-based filtering

README.md, src/matUtils/README.md, src/matUtils/uncertainty.cpp
I've written a first draft matUtils README. The formatting is basic and could be improved- looking for feedback there. Alongside this, I've updated the main README to only briefly describe matUtils and link to the matUtils-specific README (well, specifically to the matUtils README on the main Usher repository master branch). 
I've also cleaned up some of my code comments along the lines of your comments on my last PR, breaking up long lines and moving comments to their own lines. I've also added some paragraph comments describing the method and purpose of each of the uncertainty metrics we currently support in matUtils uncertainty.
=> Comment reformat and matUtils README drafting

src/matUtils/README.md, src/matUtils/main.cpp
Sorry for not staying on the ball with this in the last batch of changes. The help strings and README should reflect the most recent use of command names (old prune = new filter), plus the summary module should actually be an option now (somehow the summary src got committed but the actual parsing of a summary command did not). 
Pretty much everything in this PR except for the summary command parsing will be overwritten with the shift to using extract for most functionality this week, but this will hopefully make things usable in the next couple days.
=> Quick Documentation Fixes

src/matUtils/filter.cpp, src/matUtils/main.cpp, src/matUtils/select.cpp, src/matUtils/summary.cpp, src/matUtils/uncertainty.cpp, src/mutation_annotated_tree.cpp
To follow up with the biggest PR, let's do the smallest. This includes a change to defining the help string just once and referring to it as necessary, the addition of a bool in extract for checking whether the user actually specified any output and printing a warning if not, and an update to the uncertainty command to have a default behavior of checking all samples in the tree as intended.
=> A small, warning-and-text based PR

src/matUtils/README.md, src/matUtils/describe.cpp, src/matUtils/describe.hpp, src/matUtils/main.cpp, src/matUtils/summary.cpp
This PR is fairly small. 
It has one primary new feature, which is a new argument for extract which writes the mutations assigned to every node across a subtree/tree in dfs order to a text file (-A).
It includes additional warning messages and verbosity around clade and sample selection, especially when multiple clades/mutations are selected and at least one of them is invalid/has no samples associated with it. Choosing some kind of output argument is also now a requirement and extract will throw an error if no valid output is selected before calculating anything.
BUGS FIXED:
1. Excessive samples names being printed when representative tree output is selected alongside -S for sample paths
2. Use of output directory option when not setting -S or -C tries to write to an invalid file name
3. …
=> Bugfixes and Node Mutation printing

src/matUtils/convert.cpp, src/matUtils/extract.cpp, src/matUtils/main.cpp, src/matUtils/select.cpp, src/matUtils/select.hpp, src/matUtils/summary.cpp, src/matUtils/uncertainty.cpp
This PR includes two new arguments to extract, -u and -b. 
-b filters on the maximum number of mutations per step (branch length) in the history of the sample back to the root and is a result of a discussion with Angie and Russ about how to approach samples with odd histories. This does actually count the number of unmasked mutations and not just look at the branch length attribute (open to opinions on this decision). Max branch length *can* be zero, and if its set as such it gets samples which are 0 parsimony, no mutation children of the root node (identical to reference).
-u is a simple new output of just dumping the identifiers of selected samples to a text file; this is something I realized would be useful as I was working on example workflows in the wiki, specifically for supporting …
=> New extract arguments, updated help messages, and a couple bugfixes

src/matUtils/extract.cpp
Bryan brought to my attention during benchmarking that I had a really naive implementation related to --prune in matUtils extract (checking membership in a vector instead of a set, quadratic when it could be linear). I've made a very simple change- to using std::unordered_set- which significantly reduces total runtime for --prune commands with large sample queries. This was a naive mistake on my part and I will endeavor not to repeat it. I'm opening the PR now to make sure it gets into the next matUtils release.
=> A very, very small PR to significantly improve extract -p performance 

src/matUtils/README.md, src/matUtils/filter.cpp, src/matUtils/select.cpp, src/matUtils/select.hpp, src/matUtils/summary.cpp, src/matUtils/uncertainty.cpp
This PR is a revision of behavior around using the node branch length attribute where its not appropriate or relevant in matUtils, replacing it instead with the more consistently parsimony-relevant mutation vector size. Also includes some README updates that slipped through.
=> .branch_length is dead, long live .mutations.size()

src/usher.cpp
A couple lines of '#if DEBUG' code had "missing_sample" instead of "missing_samples", so there was a compile error when compiling with DEBUG=1.
=> Typo fix for '#if DEBUG' code

src/matUtils/mask.cpp, src/matUtils/mask.hpp
This relatively straightforward feature renames all samples to random strings and removes all their mutations. Feature is a request from Angie to support Pangolin lineage assignments and other GISAID related concerns. It can't be set at the same time as renaming because it scrambles sample names.
A simplified tree is substantially smaller in file size than the full tree, given the ability to condense previously uncondensable samples, and saves/loads more quickly. Samples placed on it are likely to have equal or higher parsimony scores to a similar placement on the full tree, equal where they are off preexisting internal nodes and higher where they could have generated a new internal node with a sample that shares their otherwise private mutations in the full tree. Clade lineage assignment …
=> Adding basic tree simplification to matUtils mask

src/matUtils/annotate.cpp, src/matUtils/annotate.hpp
This change adds several options to matUtils annotate:
--output-directory/-d : like matUtils extract, directory where output files are written, defaults to ./.
--write-mutations/-u : write a file containing mutations that exceed --allele-frequency/-f.
--write-details/-D : write a file with details about clade root node and candidate nodes.
--clip-sample-frequency/-p : max frequency of exemplars in descendants of candidate node to consider when sorting (default 0.1).
In addition to applying -p when sorting, the product of clipped sample frequency * overlap * overlap (where overlap is the
proportion of exemplars that are descendants of the candidate node) is compared, instead of first comparing sample frequency and then overlap.  This gives more weight to overlap, while still allowing a …
=> Add new options to matUtils annotate for output and sorting of candidate nodes

CMakeLists.txt, src/import_vcf_fast.cpp
The parser is in import_VCF_fast.cpp. The interface is Parsed_VCF_Line struct at line 11, which contain a hash map of samples to their non-ref allele (samples with ref alleles are omitted), and a mutation prototype, which only chromosome, position, and ref_nuc is valid. 
The output port is  tbb::flow::output_port<0>(parser), and the consumer stage can be chained at line 161.
I don't have time to integrated into usher. I will continue merging it after I debugged tree optimization maybe one week later.
=> parallelized VCF parser

src/matUtils/extract.cpp, src/matUtils/select.cpp, src/matUtils/select.hpp, src/matUtils/uncertainty.cpp, src/matUtils/uncertainty.hpp
This PR is focused on an overhaul to matUtils uncertainty, which combines the output files, so that both EPPs and neighborhood size are calculated and saved together into a single output file (compatible with -M on extract downstream!), and removes the total tree parsimony score option as matUtils summary does that now and the function is essentially deprecated. I also added an option to produce a two-column tsv of placement locations and original sample identifiers, including the original samples themselves, to improve equally parsimonious placement location visualizations. 
It also includes two new arguments for matUtils extract -H and -z. -H selects all samples for which the indicated string is a substring of the sample identifier (e.g. -H USA will get all samples with USA in the …
=> matUtils uncertainty rework, new selection features, general tweaks

src/matUtils/convert.cpp, src/matUtils/extract.cpp
VCF dump was parallelized with tbb::parallel_pipeline, (the serial_in_order flag make sure pos is sorted), so dumping VCF won't take longer than matOptimize now :).
There is no change to command line interface.
=> Parallelize VCF dump

src/matUtils/common.hpp, src/matUtils/convert.cpp, src/matUtils/convert.hpp, src/matUtils/select.cpp
This is a PR that includes a way to do parallel subtree extraction (via -N). The idea is to use tbb objects for threadsafe bookkeeping of what we have already seen in previous subtrees and to structure the bookkeeping in a more intuitive way. Most of what is new is in convert.cpp (see also the needed get_nearby() predeclaration in convert.hpp). I suspect the same basic logic could improve the existing minimum subtree extraction when tons of samples are specified. 
@jmcbroome it would be wise to make sure I did not break any of the intended usage of this function. Also @yatisht, it is worth taking a look at how I did this since I am relatively new to tbb. I suspect there are ways to improve. 
This PR also removed the "selected samples only" metadata extraction for jsons since we may want …
=> matUtils: parallel minimum subtree extraction using tbb objects for bookkeeping

src/matUtils/extract.cpp
This is just making use of the new filter_master option to keep clade annotations when the matUtils extract -r/--get_representative option is used, since matUtils extract -r is for use with clade annotations.
=> Use the new option to keep clade annotations for extract -r.

src/usher.cpp
* -n/--no-add prevents new samples from being added to the tree, so that the
tree structure stays constant regardless of how many samples are placed.
* -D/--detailed-clades includes the new clade assignment histogram in
clades.txt (the default behavior is to print only the assigned clade
for backward compatibility).
=> New options for pangolin clade assignment

src/matUtils/convert.cpp, src/matUtils/extract.cpp, src/matUtils/select.cpp, src/matUtils/uncertainty.cpp
This PR should skip missing samples passed to select.cpp:get_nearby(). The previous version would choke on the assert(), but in batch mode this can be very annoying. It now prints an error and all calls check if the returned vector is empty and continue.
=> skip missing samples

src/usher.cpp
Necessary when some samples are not placed, for example due to exceeding --max-uncertainty-per-sample.
=> Check best_clade_assignment.size() when writing clades.txt

src/matUtils/extract.cpp
Don't error out about 'no output files requested' when -x and/or -X is given because they cause usher-style output files to be written.
=> matUtils extract: count -x / -X as output

src/matUtils/annotate.cpp, src/matUtils/annotate.hpp, src/mutation_annotated_tree.cpp
This adds a third method of assigning clades to nodes: a TSV input file with clade name and mutation path, like the first and third columns of output from matUtils extract --clade-paths (and no header line).  Each mutation path is followed from root by finding a child node with the exact same set of mutations as each element in the path.  If the terminal node in the path is found, then the clade is annotated at that node; otherwise, matUtils exits with an error; someone will have to look at the path and the tree and determine how the path needs to be updated.  I have tested on the 2021-07-13 UCSC tree and some small trees recently created using matUtils extract --get-representatives 50 for the pangolin lineageTree.  I hope that this will support manual tweaks to nodes/paths found by …
=> New matUtils annotate option --clade-paths <filename>

src/matUtils/filter.cpp, src/matUtils/summary.cpp, src/mutation_annotated_tree.cpp
Recently a protobuf from the new matOptimize had some nodes with 0 clade_annotations while the tree was supposed to have 2 annotations (and most nodes did have 2).  This caused a segv in usher when assigning clades because it assumed that all nodes would have the same number of clade_annotations.
Feel free to reject if you would rather exit with an error instead, but this branch includes a change to get_clade_assignment in mutation_annotated_tree.cpp to silently treat a node with fewer annotations than expected as if it were simply unannotated (empty string for annotations) instead of getting a segv.
I also added a new item to the matUtils summary --aberrant report, for nodes with the wrong number of clade_annotations.  That could be useful for testing while adding new features that …
=> Missing clade annotations: don't segv; report in matUtils summary --aberrant

src/mutation_annotated_tree.cpp
When updating names with matUtils mask --rename, occasionally I've been bitten by a sequence being in the tree with both old and new name.  Then, renaming the old name to the new name means that there are two samples in the tree with the same (new) name.  That didn't cause any error for matUtils mask --rename, but the resulting protobuf would get an error when loading it with matUtils summary or other programs.
This change causes matUtils mask --rename to exit with an error if the new name is already in the tree.
=> matUtils mask --rename: check for duplicate names

src/matUtils/describe.cpp, src/matUtils/describe.hpp, src/matUtils/extract.cpp
matUtils extract --clade-paths was gathering a list of all clades annotated in the tree and passing that list to clade_paths which then checked each annotation to see whether it was in the list -- unnecessary.  clade_paths was also checking each annotation to see whether that clade annotation had already been encountered, which would be necessary if clades were annotated on all nodes.  However, clades are annotated only at clade root nodes, so that checking is unnecessary.  
[My real reason for making these changes is that if a clade is annotated on multiple branches, then I want each of those annotations to appear in the output, not only the first one encountered.  When there are non-monophylogeny problems with the tree due to either construction methods or unmasked problematic sites, …
=> Simplify matUtils extract --clade-paths (and allow multiple paths for an annotated clade)

CMakeLists.txt
A couple targets were added to an else() clause but not the if(DEFINED Protobuf_PATH) clause, and then referenced below which caused an error when -DProtobuf_PATH was used as in installCentOS.sh.  This adds the targets so that -DProtobuf_PATH works again.
=> Add compareVCF and rename_fasta to if(DEFINED Protobuf_PATH) clause of CMakeLists.txt

src/matOptimize/mutation_annotated_tree.hpp, src/matOptimize/stack_allocator.hpp, src/matOptimize/transpose_vcf/transposed_vcf_patch.cpp
It seems GCC 4 just checked a few things more carefully, we probably don't need to update GCC.
=> Fix gcc4 build

src/matOptimize/condense.cpp, src/matOptimize/import_vcf_fast.cpp, src/matOptimize/transpose_vcf/transposed_vcf_patch.cpp
I moved naming of condensed nodes out of parallel section, and connect decompressor and line_parser after line_parser is connected to state assigner. This seems to solve the segfaults when I run with -r 0 -n -o /dev/null as a quick way to get parsimony score, but I don't know how this solves it. More testing may be necessary.
=> Avoid race in condense nodes

src/matUtils/introduce.cpp, src/matUtils/introduce.hpp
This smaller PR, partially inspired by the recent issues thread, includes the following updates:
1. A new option, (-l), which causes only clusters that were active at least as recently as the date string passed in with -l to be reported in the output.
2. Clusters are now sorted in the output by number of samples / weeks active instead of number of samples / days active.
3. Significantly improved error handling of unparseable dates and clusters without any parseable dates with and without metadata file input.
=> Updates to Introduce- new option and QC

src/matUtils/convert.cpp, src/matUtils/convert.hpp, src/matUtils/extract.cpp, taxodium.proto
Adds `--title` and `--description` options to `matUtils extract` for use with `--write-taxodium` (reflecting the Taxodium pb change [here](https://github.com/theosanderson/taxodium/commit/427cb457633e13f214763fd7678634ffb1e73b15)).
e.g. `matUtils extract --write-taxodium out.pb -i in.pb -g genes.gtf -f reference.fasta -M metadata.tsv --title "Taxodium Tree" --description "Description of the tree."`
=> Title and description fields for Taxodium protobof output

workflows/README.md, workflows/Snakefile
This is a small update to add an introduce workflow for the snakefile. 
This can be run via : 
snakemake --use-conda --cores [num threads] --config FASTA="[user_fa]" RUNTYPE="introduce"
If users add a date string to their sample IDs in the fasta, it will be parsed correctly. Otherwise, clusters returned will have the field "no-valid-date".
=> add introduce workflow

src/matUtils/convert.cpp, src/matUtils/convert.hpp, src/matUtils/extract.cpp, src/matUtils/translate.cpp, src/matUtils/translate.hpp, taxodium.proto
Introduces ability to add generic metadata to Taxodium-format exports (#154) and adds a fix for amino-acid coloring (#149)
1. Some changes to the way metadata is read are added. Column headers are now used to determine metadata types. Columns may be in any order, and the following columns are explicitly looked for: `strain` (the sample ID),  `genbank_accession`, `date`, `country`, `pangolin_lineage`. These names match the column names of metadata from the [FTP site](https://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/).
2. The `country` and `pangolin_lineage` fields, if present, are added to the protobuf as `MetadataSingleValuePerNode` types as per the latest Taxodium [proto file](https://github.com/theosanderson/taxodium/blob/9ef607a41bbf6991f07c6ded44863be3cc992e39/public …
=> Generic metadata for Taxodium export and amino-acid coloring fix

src/matUtils/convert.cpp
This PR improves the memory efficiency in json extraction by declaring the iterator "const". In the previous version the metadata objects were copied to each thread.
=> improve memory efficiency in json extraction

src/matOptimize/import_vcf_fast.cpp
Buffer at most 1 GB as a workaround for zlib buffer size limit. It will take some time to switch to direct handling of uncompressed VCF and I-SAL for compressed VCF.
=> Cap buffer size

install/environment.yml
Intel MPI is not available on mac, so switch back to openmpi on conda local install.
=> switch back to openmpi

src/matUtils/extract.cpp, src/matUtils/introduce.cpp
This PR includes a quick request from @russcd this morning to whitelist samples that would otherwise be pruned or not included, added to matUtils extract. It takes a simple list of samples to always retain, not otherwise manipulable or combined with other selection logic. 
Additionally, this PR includes some ongoing work on my part to clean up, refactor, and do some optimizations to matUtils introduce ahead of publication. It also includes a bugfix that will change exactly what clusters are called when I propagate it to the website. It is notably faster and should be somewhat better for memory as well.
=> Whitelist in matUtils extract + refactoring of introduce

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, CMakeLists.txt, src/mutation_annotated_tree.cpp, src/mutation_annotated_tree.hpp, src/ripples/main.cpp, src/ripples/ripples_fast/main.cpp, src/ripples/ripples_fast/ripple_aux.cpp, src/ripples/ripples_fast/ripple_merger.cpp, src/ripples/ripples_fast/ripples.hpp, src/ripples/ripples_fast/ripples_mapper.cpp
It now takes 1 instead of 4 hours on the May 25 tree. It can still be faster, and more testing on other trees is needed.
Other than the is_sibling columns, the output match. I feel these columns are not set in the original ripples if the node is not optimal. (The only update to node_has_unique is at lines 165-195 in usher_mapper.cpp ) This version update it for all the node (correctly, because donor/acceptor parsimony score columns match, and usher_mapper.cpp:503 will artificially increase the parsimony score if it is placed as children).
=> faster Ripples 

src/matUtils/convert.cpp, src/matUtils/mask.cpp
This small PR addresses an issue Angie found with my implementation of mutation masking and [this issue about JSON line filtering](https://github.com/yatisht/usher/issues/228). Local testing indicates that the latter change doesn't cause problems for locally generated files, but as I'm not directly familiar with the online UShER interface or the data it loads into the JSON output, @AngieHinrichs may want to verify that this behaves as expected and resolves the indicated issue as Roemer thinks it should.
=> Small pull request including bugfix and JSON filtering

src/usher_common.cpp
node_has_unique should be indexed by node offset best_j_vec[k] not just k.  Fixes #233
=> Fix indexing bug that can cause overspecific clade assignment

src/matUtils/annotate.cpp, src/matUtils/annotate.hpp, src/matUtils/summary.cpp
Currently in `matUtils annotate`, `--clade-mutations` and `--clade-names` can be used simultaneously with `--clade-mutations` taking precedence, but `--clade-paths` is mutually exclusive with all other `--clade-*` options.  This change allows all three of `--clade-paths`, `--clade-mutations` and `--clade-names` to be used simultaneously, with `--clade-paths` taking highest precedence.  (The options can still be used separately.)
When all three options are used together, first we try the paths file; any clade annotated by path will be ignored if we encounter it again in the mutations or names files.  Then we try the mutations file and then names as fallbacks for paths that can't be found because the order of mutations has changed.  This combines the speed of the paths method with the …
=> Allow --clade-paths to work in conjunction with --clade-mutations and --clade-names

src/matUtils/select.cpp
`get_short_paths` needs to return the intersection of `good_samples` with `samples_to_check`.  This PR changes `good_samples` into an unordered set instead of vector, and adds a version of `sample_intersect` that takes an unordered set instead of vector, so the intersection is O(N)*O(constant) instead of O(N)*O(M) which is impractical when both N and M are ~10M.
This fixes the specific problem with `--max-path-length` in #243, but extract.cpp calls `sample_intersect` in several places with two vectors as input; unless one of the vectors is always very small, it would be a good idea to use `std::unordered_set` instead of `std::vector` for at least one of the sets (ideally the larger set; and it wouldn't hurt to use unordered set in all cases).
=> get_short_paths: intersect good_samples with samples_to_check using std::unordered_set

src/matUtils/extract.cpp, src/matUtils/select.cpp, src/matUtils/select.hpp
This adds two options to `matUtils extract`: `--within-distance [filename]` and `--distance-threshold [int]` which are used to write a TSV file listing all sample IDs within `distance-threshold` of the selected samples.
E.g. `matUtils extract --within-distance output.tsv --distance-threshold 4 -s input_samples.tsv -i tree.pb.gz`
The first column in the TSV output contains one sample from the input set per line, and the second column is a comma-separated list of all samples within the specified threshold of that line's sample.
This also fixes a small bug in the logic for `extract --closest-relatives`
=> Add --within-distance to matUtils extract (output all samples within k mutations of target samples)

src/matUtils/select.cpp
Fixes a bug in the nearest neighbor and within-distance functions (in certain cases the branch length to the target node was not being included in the calculation)
=> Nearest neighbors / within-distance fix

src/mutation_annotated_tree.cpp
@mdperry and I independently found a SEGV condition when switching to the latest version of usher/matUtils: when MAT::get_subtree is called _without_ keep_clade_annotations=true, and the tree contains clade annotations, get_subtree creates new nodes with clade_annotations size 0 but then attempts to copy the existing node's clade annotations.  This was an unintended side effect of 052cf4a6 (which solved a different problem that could occur when keep_clade_annotations=true is passed in).
The solution is to limit the loop that copies clade annotations into the new node to the minimum of num_annotations (which is 0 when keep_clade_annotations is false) and source node's clade_annotations.size(), so overrun of clade_annotations is prevented for both the new node and the existing node.
=> Fix segv when get_subtree is called without keep_clade_annotations on tree with annotations

src/matUtils/summary.cpp
`matUtils summary --sample-clades` crashed when a node had fewer than expected clade annotations -- same situation as for `matUtils extract` in #256.
=> Fix segv in matUtils summary -C when a node doesn't have the expected number of clade annotations

src/usher-sampled/driver/main.cpp, src/usher-sampled/import_vcf.cpp, src/usher-sampled/usher.hpp, src/usher-sampled/utils.cpp
usher-sampled can read maple diff file through --diff argument and --ref argument (maple diff file do not contain reference allele). I am running out of letters for the single letter options, so they don't have a single letter option.
=> usher-sampled support MAPLE input

src/matOptimize/Profitable_Moves_Enumerators/Bounded_Search.hpp, src/matOptimize/Profitable_Moves_Enumerators/Profitable_Moves_Enumerators.hpp, src/matOptimize/Profitable_Moves_Enumerators/check_move_profitable.cpp, src/matOptimize/Profitable_Moves_Enumerators/check_move_profitable_LCA.cpp, src/matOptimize/Profitable_Moves_Enumerators/downward_integrated.cpp, src/matOptimize/Profitable_Moves_Enumerators/upward_integrated.cpp
It only includes nodes on the path from source to destination, excluding source and destination, because during the search phase we assume all moves will split the branch between the destination and the parent of the destination node, creating a new node. I am not sure how to pass this information to larch. (If it creates a zero-length branch, it will be cleaned up at the very end.)
Maybe wait until the larch team confirms it is useful to merge this?
=> Make nodes with changed major allele set available to larch through the callback

src/matUtils/mask.cpp
For reversion mutations in the tree, mut_nuc is the same as ref_nuc and par_nuc is the change being reverted.  `matUtils mask --mask-mutations` was comparing ref_nuc instead of par_nuc, so it was unable to recognize reversions specified in its input file that were present in the tree.  (For mutations parsed from the input file, ref_nuc is set to the same value as par_nuc, but that is not the case for mutations in the tree.)
=> branch-specific masking: compare par_nuc not ref_nuc

src/usher-sampled/driver/main.cpp, src/usher-sampled/import_vcf.cpp
Also make diff format more permissive -- infer a 1 for -/N if missing.
=> usher-sampled : Exit properly when there is no sample to place

src/matUtils/annotate.cpp, src/matUtils/describe.cpp, src/matUtils/describe.hpp, src/matUtils/extract.cpp, src/matUtils/select.cpp, src/matUtils/select.hpp
I added two options to matUtils extract to prune problematic sequences and branches from the SARS-CoV-2 tree before making a minimized tree for use with pangolin:
* `--node-stats filename` writes out various statistics of each internal node and sample, including the number of reversions to reference since the most recent ancestor annotated as a clade/lineage root.  (For recent pangolin data releases, I've been pruning samples with 2 or more reversions since lineage root.)
* `--max-mutation-density D` removes samples descended from nodes whose "mutation density" (sum of mutation counts divided by number of leaves) is greater than D (I've been using D=2 for pangolin), with several exceptions:
* don't mark an annotated clade root for removal even if it or an ancestor has a high mutation …
=> new options for matUtils extract: --max-mut-density, --node-stats

src/matOptimize/mutation_annotated_tree.cpp, src/matOptimize/mutation_annotated_tree.hpp, src/usher-sampled/driver/client-example.c, src/usher-sampled/utils.cpp
* Revert back to using a process for newick writing. I forgot that the tree is getting condensed while writing pb.
* Parallelize subtree extraction, and fix subtree that does not contain any new sample.
=> Fix subtree extraction && fork for newick writing

src/matOptimize/mutation_annotated_tree.cpp, src/usher-sampled/import_vcf.cpp
* Relax assertions to allow an empty starting tree and 0-position.
* Make starting subtree index start with 1 as in the old usher.
=> Handle empty tree and compatibility changes

src/usher-sampled/driver/main.cpp
Add @yceh's new option `--no-ignore-prefix` from usher-sampled-server client requests to usher-sampled.  (Mirrors corresponding addition to src/usher-sampled/driver/socket.cpp lines  [390](https://github.com/yatisht/usher/blob/d20fddf4e751995bfae2c74f591b5693b9c8a654/src/usher-sampled/driver/socket.cpp#L390) and [331](https://github.com/yatisht/usher/blob/d20fddf4e751995bfae2c74f591b5693b9c8a654/src/usher-sampled/driver/socket.cpp#L331))
=> Add --no-ignore-prefix to usher-sampled (from usher-sampled-server)

src/matOptimize/mutation_annotated_tree.cpp, src/matOptimize/mutation_annotated_tree_node.cpp, src/usher-sampled/driver/client-matutil.c, src/usher-sampled/driver/socket.cpp
* Fix duplicated sample node in mutation path output
* Add server option for extracting subtree from existing samples using --existing_samples argument and the output options from usher. See src/usher-sampled/client_matutil.c for example.
=> subtree extraction server and mutation path fix

src/usher-sampled/driver/main.cpp
Usher-sampled needs one thread for tree modifications and at least another one for search. If -T1 is specified, it will deadlock.
=> Use at least 2 threads for usher-sampled

src/usher-sampled/place_sample.cpp
The search dispatcher may increment the current sample index before the tree modification thread reads it, which may finish early.
=> Fix race condition when placing sample

src/ripples/ripples_fast/main.cpp
The merger didn't expect the parsimony threshold to be negative (which can happen for user-specified samples) internally and use unsigned int, so I now gate the negative parsimony thresholds in the main function.
=> Fix negative parsimony threshold

install/environment.yml
Removing the defaults channel resolves build issues currently affecting Ubuntu 22.04 and 20.04. I believe the reason is that there is a conflict between one of the defaults channel compilers and TBB or another package. The conda forge version does not produce the same error and builds correctly.
=> removed "-defaults" channel

src/matUtils/extract.cpp, src/matUtils/select.cpp, src/matUtils/select.hpp, src/matUtils/summary.cpp, src/matUtils/summary.hpp
This PR addresses two issues. 
First, it addresses https://github.com/yatisht/usher/issues/303. Typically, only metadata for samples in the users query set is loaded into memory. This was originally implemented to reduce the memory footprint of our approach. However, in cases with -N, -K, and similar, users may want full metadata to be available for any and all samples in their output, including non-query context samples. Accordingly, I have added a flag (without a single letter accompanying it) `--load-all-metadata` to matUtils extract indicating that all available metadata should be loaded and available for output. 
Second, it addresses https://github.com/yatisht/usher/issues/326. This is a significant rework of the implementation and output of `matUtils summary --haplotype`. It is now …
=> --haplotype rework and metadata loading flag

src/usher-sampled/place_sample.cpp
Fix segfault when the target node to place sample is the root node. (It comes from identification of the root node versions).
=> fix computing root mutation

src/matUtils/fix.cpp, src/matUtils/fix.hpp, src/matUtils/main.cpp, src/matUtils/mask.cpp, src/mutation_annotated_tree.cpp, src/mutation_annotated_tree.hpp
This bundles several improvements to matUtils.  Let me know if you would prefer for them to be pulled out into separate PRs.
1. I added a new subcommand `fix` to find and fix a recurring pattern that causes trouble for lineage designation: often there is a node whose mutation is simply a reversion of its grandparent's mutation, for example the final node in a path like this:
`... > A1C > G2T > C3A > T2G`
In that case it would be preferable to move that final node to `... > A1C > C3A`, i.e. to move it to become a child of its great-grandparent with only its parent's mutation.  As long as the grandparent, parent and final node all have only one mutation each, that operation is parsimony-preserving.  It represents two independent occurrences of C3A on the A1C branch, as opposed to only one …
=> matUtils updates: new subcommand "fix"; improvements to MAT::Tree:move_node and mask --move-nodes

src/matUtils/convert.cpp
Addresses https://github.com/nextstrain/auspice/issues/1756 from the matUtils side by providing a (bogus) divergence value when converting to JSON. This makes the resulting JSON align closer to the schema that Auspice expects, and this enables radial and unrooted view to work properly.
Thanks to @jameshadfield for pinpointing exactly what was missing from the matUtils JSON, and @kvargha for finding the very silly Dockerfile issue that was preventing me from testing my changes properly!
=> Fix auspice radial and unrooted views

src/matUtils/filter.cpp
This addresses two corner cases that we hadn't thought through yet for --reroot:
* First, when rerooting to a leaf node, that node was converted into an internal node (the new root), losing its leaf status, so when the result was written out, the tree no longer had that leaf.  To fix this, when rerooting to a leaf, we add a new leaf with the same name on the new root node.
* Second, when the old root had no leaf children and only one internal node child, after rerooting it became a new leaf node, keeping its original ID of `node_1`.  However, the saved protobuf could not be read back in by matUtils because when parsing the Newick string, `node_1` is assigned to the first node encountered, and it is an error for any subsequent node to have the name `node_1` (even a leaf) because `node_1` …
=> matUtils extract --reroot: retain rerooted leaf, rename leaf from former internal node

install/Dockerfile
Updates the Ubuntu base image to in order to upgrade `sed` to 4.8. 22.04 (jammy) was chosen as the new base image as usher does not compile when the base image is set to 24.04 (noble).
I tested the resulting Docker image as described in #370 and confirmed that this fixes that issue, but I did not extensively test other usher functions.
=> Update base image, fix #370

src/matOptimize/main.cpp
Using -D (--diff_file_path) resulted in an error message because the option-checking logic did not have a case for using -D instead of -v (VCF). This adds the case for -D and updates the error message that describes acceptable input options.
=> matOptimize: Allow -D option

src/matUtils/mask.cpp
Right now, `matUtils mask -h` correctly returns 0, but it prints "stuck here" to stderr beforehand. This fixes that, plus some tiny inconsistencies in other prints.
=> Small print changes to matUtils mask

src/matUtils/convert.cpp, src/matUtils/convert.hpp, src/matUtils/extract.cpp
The new --write-diff option generates a [MAPLE](https://github.com/NicolaDM/MAPLE)/"diff" output file with the substitutions for each sequence in the selected subtree.  I used this recently to make input for [MAPLE/SPRTA](https://github.com/NicolaDM/MAPLE#branch-support) analysis of the UShER tree in https://www.biorxiv.org/content/10.1101/2024.04.29.591666v1 (under review).
=> Add --write-diff option to matUtils extract

src/matOptimize/import_vcf_fast.cpp, src/usher-sampled/import_vcf.cpp
matOptimize can hit a SEGV when the same sample name is used for multiple sample columns in VCF, and sample names should be unique in VCF.  Add a test for duplicated samples to matOptimize's VCF-reading code and exit when found.  Change usher-sampled's VCF reader to exit instead of warning and continuing when duplicates are found, so the error can be found as early in the pipeline as possible.
=> Error exit when VCF has duplicated samples
