src/matUtils/convert.cpp, src/matUtils/convert.hpp, src/matUtils/extract.cpp
Edited extract.cpp, convert.hpp, convert.cpp to add option to write trees as JSON files. Have tested and is compatible with auspice import.
=> Adding JSON writer

src/matUtils/filter.cpp
Bryan brought it to my attention today that the polytomy resolution routine did not yield a fully binary tree, because of 1. internal nodes with 3 or more children which are not polytomies but continue on to be clades 2. internal nodes that somehow only have one child.
I've updated the routine to check for any and all internal nodes with other than 2 children, removing nodes with 1 and resolving ones with 3 or more. 
I would have pushed this directly to the Usher main repository but git was giving me permission denied, though I thought you'd added me as a direct contributor so I could push fixes straight. Not sure if that's just an oversight or if I need to fix something with my git keys. Either way, faster to open and merge a PR to get this into Bryan's hands to redo a little …
=> Change polytomy resolver to fully resolve entire tree

src/matUtils/uncertainty.cpp
very small wording adjustments in uncertainty
=> small wording adjustments in uncertainty

Dockerfile
UShER workflow WDL in progress...
=> adding faSize and faSomeRecords to the Docker container

src/matUtils/mask.cpp
Instead of condensing all the leaves that have had their private mutations removed and their names anonymized, we can use the same logic as condense_leaves to identify the sets of identical leaves; for each set, instead of creating a new condensed node and listing all the anonymized names, simply remove all but the first leaf.
For a COG-UK tree with 433k leaves in 153k distinct sets, replacing the condensed nodes and lists with single anonymized leaves reduced the protobuf size ~40%.
=> matUtils mask --simplify: prune instead of condensing identical leaves

src/matUtils/convert.cpp
This PR will print sample metadata in the output table when the minimum number of subtrees output is requested.
=> print relevant metadata to output table

parsimony.proto
Thanks so much for talking me through the proto structure. I made these notes for myself. I thought I'd raise a PR in case they'd be useful, but don't feel under pressure to review/accept.
Thanks again!
=> Add some comments to parsimony.proto

parsimony.proto
(I think I've got this right? Sorry for the change)
=> Proto comments: clarify that the type of traversal is preorder

src/matUtils/extract.cpp
When producing usher-style subtree(s), optionally also write a clades.txt so the web interface can show tree-annotated clades for selected samples.  I also fixed a couple imbalanced/nested timer.{Start,Stop}s.
=> matUtils extract: usher-style clades.txt for usher-style subtrees

workflows/README.md, workflows/Snakefile, workflows/usher.yaml
This is a quick snakemake file for three workflows. 
1. Basic usher.
2. matUtils to extract subtrees around each user sample in auspice compatible format. 
3. ripples for detecting recombinants in user provided samples.
=> simple snakemake

src/matOptimize/main_helper.cpp, src/matOptimize/transpose_vcf/transposed_vcf_patch.cpp
Sorry, forgot to clean nodes to search from the start of each round in last commit, so it sometimes segfaults when searching for a deleted node.
=> Forgot to clear nodes to search from last round

src/matUtils/filter.cpp
When rerooting, maintain the condition that the root node has no mutations, i.e. it represents the reference sequence for all nodes' mutations, by moving and inverting mutations when moving nodes.  After rerooting, scan the tree's mutations for ref_nuc values that need to be updated.  This is necessary for re-rooting the big tree from lineage B to lineage A for pangolin, which makes VCF relative to lineage A so it needs a protobuf with lineage A root and reference.
This approach will not work for extracted subtrees whose root has mutations relative to the reference, but I can't imagine why we would want to reroot those, so I exit w/error if root has mutations.  If we need to support rerooting of extracted subtrees someday, then "we" can implement it at that time.  :)
=> matUtils extract --reroot: update node mutations to maintain root as the (new) reference

src/matOptimize/main.cpp, src/matOptimize/main_helper.cpp, src/matOptimize/mutation_annotated_tree.cpp, src/matOptimize/mutation_annotated_tree.hpp
Also, reasonable default for minimum improvement (0.5%) which will stop on the 3M tree in ~7h with 60 threads.
=> Searching nodes to search faster with radius doubling 

src/usher_common.cpp, src/usher_server.cpp
**How to use usher_server**
1. Compilation
-When compiling, add the CMake flag  -DUSHER_SERVER=TRUE
2. Input arguments for usher_server
-a: argument directory. This directory would contain files in which arguments are contained.
-i: list of mutation annotated trees(MATs). This file would contain the names of the protobuf files that 
store MATs. Each line would have a name of one protobuf file.
-s: sleep length in milliseconds. When there are no files in the argument directory, this is how long the 
program will wait for before checking again. Default is 100 milliseconds
-c: termination character. This is a character that will determine when the file in the argument directory 
is ready to be read. This will be specified with the integer ASCII code value. When the specified
character is at …
=> Added some comments on usher_server

install/environment.yml, src/matOptimize/Profitable_Moves_Enumerators/Profitable_Moves_Enumerator.cpp, src/matOptimize/Profitable_Moves_Enumerators/Profitable_Moves_Enumerators.hpp, src/matOptimize/Profitable_Moves_Enumerators/upward_integrated.cpp, src/matOptimize/detailed_mutations_store.cpp, src/matOptimize/main.cpp, src/matOptimize/optimize_tree.cpp, src/matOptimize/tree_rearrangement_internal.hpp
Adding back tree drifting, but performance is quite bad on move recycling.
I removed the version locking of protobuf and cmake, because miniconda complains about conflict when I install it, maybe we need a more recent version.
Thanks!
=> Tree drifting + Intel MPI

CMakeLists.txt
This may potentially fix #224, but I am not really sure.
=> fix centos build?

CMakeLists.txt
Another try at #224. The file list for the two ways to generate protobuf should be the same. I forgot to update the one when Protobuf_PATH is defined.
=> keep protobuf generation in sync

src/matOptimize/main.cpp, src/matOptimize/mutation_annotated_tree_load_store.cpp, src/matOptimize/mutation_annotated_tree_nuc_util.cpp, src/matOptimize/transpose_vcf/transposed_vcf_patch.cpp, src/matOptimize/tree_rearrangement_internal.hpp, src/matUtils/convert.cpp
Diff file from MAPLE can now be used with reference FASTA and a Newick tree input.
Fix extra N in matUtils extract.
=> Support Diff file from MAPLE

src/usher-sampled/driver/main.cpp, src/usher-sampled/driver/socket.cpp, src/usher-sampled/import_vcf.cpp, src/usher-sampled/main_mapper.cpp, src/usher-sampled/usher.hpp, src/usher-sampled/usher_only_utils.cpp, src/usher-sampled/utils.cpp
Not sure why this only gets triggered in server mode.
=> Fix vcf loader segfault

.gitignore, src/matOptimize/mutation_annotated_tree_nuc_util.cpp, src/usher-sampled/driver/client-example.c, src/usher-sampled/driver/socket.cpp
Minor/cosmetic changes as I've been testing usher-sampled-server:
* added some details to the server option descriptions
* added outdir arg to client-example for testing simultaneous queries
* accept '*' as an alternate allele in VCF (like N; warnings were clogging stderr log)
* gitignore all build*/ directories
Thanks @yceh for the fast fixes and new features!
=> miscellaneous small changes

src/matUtils/introduce.cpp
This should fix issue #281 
@jmcbroome
=> fixes date range for introduce clusters

CMakeLists.txt, src/usher-sampled/driver/main.cpp, src/usher-sampled/driver/socket.cpp
Also print a stack trace on segfault.
=> usher-server reload fix and add version string

src/mutation_annotated_tree.cpp
This changes MAT::collapse_tree to add child's mutations to its parent node when collapsing, instead of adding parent node's mutations to its child which violated the order expected by Node::add_mutations.  This also adds an error check in add_mutations that would have caught the bug.  (In effect it was asked to evaluate A23013G > C23013A which doesn't make sense because G != C.  Now, the intended C23013A > A23013G is passed in from collapse_tree.)  
I tested this on the test case from #308 and now the collapsed path includes C23013G as it should:
```
... node_1138105:T22020C,T22054G,G23012A,C23013G,C28550A ...
```
=> collapse_tree: preserve order expected by add_mutation

README.md
=> Update link to license in README.md

src/usher-sampled/driver/main.cpp, src/usher-sampled/import_vcf.cpp
* Clear reference vector before reading reference form FASTA file.
* Ignore non-informative sites.
=> Fix diff loading with protobuf input

src/matOptimize/main.cpp
If it is equally parsimonious to place a node among a node and all its children, this will only keep one of them.
=> filter epps if they are clustered around a single node

src/matUtils/mask.cpp
Currently, matUtils mask --move-nodes requires the new parent to have all mutations found in the old parent.  However, sometimes we want to move a node to a new parent that has a mutation found not in the old parent, but in the node to be moved itself.  This change extends --move-nodes to support that case by moving the node, removing the mutation shared with the new parent from the moved node, and adding any mutations found in the old parent but not the new parent to the moved node.  Instead of comparing unordered sets of mutation strings, the code now uses vectors of mutation objects so that it can use Node::add_mutation to support a series of mutations at the same position.
=> matUtils mask --move-nodes: allow move to parent with mutation(s) of node to be moved
